version: "3.8"

services:
  handler:
    build: .
    command: python main.py
    working_dir: /usr/src/handler/
    volumes:
      - ./handler/:/usr/src/handler/
    ports:
      - 11002:11002
    env_file:
      - ./.env
    depends_on:
      - redis
  # reporter:
  #   build: .
  #   command: python main.py
  #   working_dir: /usr/src/reporter/
  #   volumes:
  #     - ./reporter/:/usr/src/reporter/
  #   ports:
  #     - 11006:11006
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - postgres
  #     - redis
  analyser:
    build: .
    command: python main.py
    working_dir: /usr/src/analyser/
    volumes:
      - ./analyser/:/usr/src/analyser/
    ports:
      - 11001:11001
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - postgres
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - ./.env
